# TCL File Generated by Component Editor 15.1
# Wed Sep 07 19:29:47 MSK 2016
# DO NOT MODIFY


# 
# acDriver "Audio Codec Driver" v1.0
#  2016.09.07.19:29:47
# audio part + i2c part for configuration
# 

# 
# request TCL package from ACDS 15.1
# 
package require -exact qsys 15.1


# 
# module acDriver
# 
set_module_property DESCRIPTION "audio part + i2c part for configuration"
set_module_property NAME acDriver
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "Audio Codec Driver"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL acDriverHw
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file acDriverHw.sv SYSTEM_VERILOG PATH ../../rtl/acDriverHw.sv TOP_LEVEL_FILE
add_fileset_file acDriver.sv SYSTEM_VERILOG PATH ../../rtl/acDriver.sv
add_fileset_file acAvalon.sv SYSTEM_VERILOG PATH ../../rtl/acAvalon.sv
add_fileset_file acGenerator.sv SYSTEM_VERILOG PATH ../../rtl/acGenerator.sv
add_fileset_file acInterface.sv SYSTEM_VERILOG PATH ../../rtl/acInterface.sv
add_fileset_file acCore.sv SYSTEM_VERILOG PATH ../../rtl/acCore.sv
add_fileset_file i2cAvalon.sv SYSTEM_VERILOG PATH ../../rtl/i2cMaster/i2cAvalon.sv
add_fileset_file i2cControl.sv SYSTEM_VERILOG PATH ../../rtl/i2cMaster/i2cControl.sv
add_fileset_file i2cLine.sv SYSTEM_VERILOG PATH ../../rtl/i2cMaster/i2cLine.sv
add_fileset_file i2cMaster.sv SYSTEM_VERILOG PATH ../../rtl/i2cMaster/i2cMaster.sv
add_fileset_file i2cTick.sv SYSTEM_VERILOG PATH ../../rtl/i2cMaster/i2cTick.sv
add_fileset_file cordicCosSin.sv SYSTEM_VERILOG PATH ../../rtl/cordicCosSin/cordicCosSin.sv
add_fileset_file cordicCosSinParallel.sv SYSTEM_VERILOG PATH ../../rtl/cordicCosSin/cordicCosSinParallel.sv
add_fileset_file cordicCosSinSerial.sv SYSTEM_VERILOG PATH ../../rtl/cordicCosSin/cordicCosSinSerial.sv
add_fileset_file cordicLUT.vh OTHER PATH ../../rtl/cordicCosSin/cordicLUT.vh
add_fileset_file cordicPkg.vh OTHER PATH ../../rtl/cordicCosSin/cordicPkg.vh


# 
# parameters
# 
add_parameter INTERFACE_TYPE STRING LEFT-JUSTIFIED ""
set_parameter_property INTERFACE_TYPE DEFAULT_VALUE LEFT-JUSTIFIED
set_parameter_property INTERFACE_TYPE DISPLAY_NAME INTERFACE_TYPE
set_parameter_property INTERFACE_TYPE WIDTH ""
set_parameter_property INTERFACE_TYPE TYPE STRING
set_parameter_property INTERFACE_TYPE UNITS None
set_parameter_property INTERFACE_TYPE ALLOWED_RANGES {LEFT-JUSTIFIED RIGHT-JUSTIFIED I2S}
set_parameter_property INTERFACE_TYPE DESCRIPTION ""
set_parameter_property INTERFACE_TYPE HDL_PARAMETER true
add_parameter DATA_WDT INTEGER 24 "width of adc/dac data, 16, 20, 24, 32"
set_parameter_property DATA_WDT DEFAULT_VALUE 24
set_parameter_property DATA_WDT DISPLAY_NAME DATA_WDT
set_parameter_property DATA_WDT WIDTH ""
set_parameter_property DATA_WDT TYPE INTEGER
set_parameter_property DATA_WDT UNITS None
set_parameter_property DATA_WDT ALLOWED_RANGES {16 20 24 32}
set_parameter_property DATA_WDT DESCRIPTION "width of adc/dac data, 16, 20, 24, 32"
set_parameter_property DATA_WDT HDL_PARAMETER true
add_parameter BCLK_DIVIDER INTEGER 2 "relative to mclk, 1, 2, 4, 6, ... or greater even number"
set_parameter_property BCLK_DIVIDER DEFAULT_VALUE 2
set_parameter_property BCLK_DIVIDER DISPLAY_NAME BCLK_DIVIDER
set_parameter_property BCLK_DIVIDER WIDTH ""
set_parameter_property BCLK_DIVIDER TYPE INTEGER
set_parameter_property BCLK_DIVIDER UNITS None
set_parameter_property BCLK_DIVIDER ALLOWED_RANGES 1:32
set_parameter_property BCLK_DIVIDER DESCRIPTION "relative to mclk, 1, 2, 4, 6, ... or greater even number"
set_parameter_property BCLK_DIVIDER HDL_PARAMETER true
add_parameter LRCK_DIVIDER INTEGER 128 "relative to mclk, must be even"
set_parameter_property LRCK_DIVIDER DEFAULT_VALUE 128
set_parameter_property LRCK_DIVIDER DISPLAY_NAME LRCK_DIVIDER
set_parameter_property LRCK_DIVIDER WIDTH ""
set_parameter_property LRCK_DIVIDER TYPE INTEGER
set_parameter_property LRCK_DIVIDER UNITS None
set_parameter_property LRCK_DIVIDER ALLOWED_RANGES -2147483648:2147483647
set_parameter_property LRCK_DIVIDER DESCRIPTION "relative to mclk, must be even"
set_parameter_property LRCK_DIVIDER HDL_PARAMETER true
add_parameter CLK_I2C_FRQ INTEGER 50000000 "input clk frequency"
set_parameter_property CLK_I2C_FRQ DEFAULT_VALUE 50000000
set_parameter_property CLK_I2C_FRQ DISPLAY_NAME CLK_I2C_FRQ
set_parameter_property CLK_I2C_FRQ WIDTH ""
set_parameter_property CLK_I2C_FRQ TYPE INTEGER
set_parameter_property CLK_I2C_FRQ UNITS Hertz
set_parameter_property CLK_I2C_FRQ ALLOWED_RANGES -2147483648:2147483647
set_parameter_property CLK_I2C_FRQ DESCRIPTION "input clk frequency"
set_parameter_property CLK_I2C_FRQ HDL_PARAMETER true
add_parameter SCLK_I2C_FRQ INTEGER 500000 "desired i2c sclk frequency"
set_parameter_property SCLK_I2C_FRQ DEFAULT_VALUE 500000
set_parameter_property SCLK_I2C_FRQ DISPLAY_NAME SCLK_I2C_FRQ
set_parameter_property SCLK_I2C_FRQ WIDTH ""
set_parameter_property SCLK_I2C_FRQ TYPE INTEGER
set_parameter_property SCLK_I2C_FRQ UNITS Hertz
set_parameter_property SCLK_I2C_FRQ ALLOWED_RANGES -2147483648:2147483647
set_parameter_property SCLK_I2C_FRQ DESCRIPTION "desired i2c sclk frequency"
set_parameter_property SCLK_I2C_FRQ HDL_PARAMETER true


# 
# display items
# 
add_display_item "" "Audio Interface" GROUP ""
add_display_item "" I2C GROUP ""
add_display_item "" "audio part" GROUP ""
add_display_item "audio part" INTERFACE_TYPE PARAMETER ""
add_display_item "audio part" DATA_WDT PARAMETER ""
add_display_item "audio part" BCLK_DIVIDER PARAMETER ""
add_display_item "audio part" LRCK_DIVIDER PARAMETER ""
add_display_item "" "i2c part" GROUP ""
add_display_item "i2c part" CLK_I2C_FRQ PARAMETER ""
add_display_item "i2c part" SCLK_I2C_FRQ PARAMETER ""


# 
# connection point acClk
# 
add_interface acClk clock end
set_interface_property acClk clockRate 0
set_interface_property acClk ENABLED true
set_interface_property acClk EXPORT_OF ""
set_interface_property acClk PORT_NAME_MAP ""
set_interface_property acClk CMSIS_SVD_VARIABLES ""
set_interface_property acClk SVD_ADDRESS_GROUP ""

add_interface_port acClk csi_acClk_clk clk Input 1


# 
# connection point i2cClk
# 
add_interface i2cClk clock end
set_interface_property i2cClk clockRate 0
set_interface_property i2cClk ENABLED true
set_interface_property i2cClk EXPORT_OF ""
set_interface_property i2cClk PORT_NAME_MAP ""
set_interface_property i2cClk CMSIS_SVD_VARIABLES ""
set_interface_property i2cClk SVD_ADDRESS_GROUP ""

add_interface_port i2cClk csi_i2cClk_clk clk Input 1


# 
# connection point acReset
# 
add_interface acReset reset end
set_interface_property acReset associatedClock acClk
set_interface_property acReset synchronousEdges DEASSERT
set_interface_property acReset ENABLED true
set_interface_property acReset EXPORT_OF ""
set_interface_property acReset PORT_NAME_MAP ""
set_interface_property acReset CMSIS_SVD_VARIABLES ""
set_interface_property acReset SVD_ADDRESS_GROUP ""

add_interface_port acReset rsi_acReset_reset reset Input 1


# 
# connection point i2cReset
# 
add_interface i2cReset reset end
set_interface_property i2cReset associatedClock i2cClk
set_interface_property i2cReset synchronousEdges DEASSERT
set_interface_property i2cReset ENABLED true
set_interface_property i2cReset EXPORT_OF ""
set_interface_property i2cReset PORT_NAME_MAP ""
set_interface_property i2cReset CMSIS_SVD_VARIABLES ""
set_interface_property i2cReset SVD_ADDRESS_GROUP ""

add_interface_port i2cReset rsi_i2cReset_reset reset Input 1


# 
# connection point codecControl
# 
add_interface codecControl conduit end
set_interface_property codecControl associatedClock acClk
set_interface_property codecControl associatedReset acReset
set_interface_property codecControl ENABLED true
set_interface_property codecControl EXPORT_OF ""
set_interface_property codecControl PORT_NAME_MAP ""
set_interface_property codecControl CMSIS_SVD_VARIABLES ""
set_interface_property codecControl SVD_ADDRESS_GROUP ""

add_interface_port codecControl coe_audMclk audMclk Output 1
add_interface_port codecControl coe_audBclk audBclk Output 1
add_interface_port codecControl coe_audAdcLrck audAdcLrck Output 1
add_interface_port codecControl coe_audAdcData audAdcData Input 1
add_interface_port codecControl coe_audDacLrck audDacLrck Output 1
add_interface_port codecControl coe_audDacData audDacData Output 1
add_interface_port codecControl coe_audMute audMute Output 1


# 
# connection point audioInterface
# 
add_interface audioInterface conduit end
set_interface_property audioInterface associatedClock acClk
set_interface_property audioInterface associatedReset acReset
set_interface_property audioInterface ENABLED true
set_interface_property audioInterface EXPORT_OF ""
set_interface_property audioInterface PORT_NAME_MAP ""
set_interface_property audioInterface CMSIS_SVD_VARIABLES ""
set_interface_property audioInterface SVD_ADDRESS_GROUP ""

add_interface_port audioInterface coe_acTick acTick Output 1
add_interface_port audioInterface coe_acAdcDataL acAdcDataL Output DATA_WDT
add_interface_port audioInterface coe_acAdcDataR acAdcDataR Output DATA_WDT
add_interface_port audioInterface coe_acDacDataL acDacdataL Input DATA_WDT
add_interface_port audioInterface coe_acDacDataR acDacdataR Input DATA_WDT


# 
# connection point acAvs
# 
add_interface acAvs avalon end
set_interface_property acAvs addressUnits WORDS
set_interface_property acAvs associatedClock acClk
set_interface_property acAvs associatedReset acReset
set_interface_property acAvs bitsPerSymbol 8
set_interface_property acAvs burstOnBurstBoundariesOnly false
set_interface_property acAvs burstcountUnits WORDS
set_interface_property acAvs explicitAddressSpan 0
set_interface_property acAvs holdTime 0
set_interface_property acAvs linewrapBursts false
set_interface_property acAvs maximumPendingReadTransactions 0
set_interface_property acAvs maximumPendingWriteTransactions 0
set_interface_property acAvs readLatency 1
set_interface_property acAvs readWaitStates 0
set_interface_property acAvs readWaitTime 0
set_interface_property acAvs setupTime 0
set_interface_property acAvs timingUnits Cycles
set_interface_property acAvs writeWaitTime 0
set_interface_property acAvs ENABLED true
set_interface_property acAvs EXPORT_OF ""
set_interface_property acAvs PORT_NAME_MAP ""
set_interface_property acAvs CMSIS_SVD_VARIABLES ""
set_interface_property acAvs SVD_ADDRESS_GROUP ""

add_interface_port acAvs avs_acAvs_address address Input 2
add_interface_port acAvs avs_acAvs_write write Input 1
add_interface_port acAvs avs_acAvs_writedata writedata Input 16
add_interface_port acAvs avs_acAvs_read read Input 1
add_interface_port acAvs avs_acAvs_readdata readdata Output 16
set_interface_assignment acAvs embeddedsw.configuration.isFlash 0
set_interface_assignment acAvs embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment acAvs embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment acAvs embeddedsw.configuration.isPrintableDevice 0


# 
# connection point i2cAvs
# 
add_interface i2cAvs avalon end
set_interface_property i2cAvs addressUnits WORDS
set_interface_property i2cAvs associatedClock i2cClk
set_interface_property i2cAvs associatedReset i2cReset
set_interface_property i2cAvs bitsPerSymbol 8
set_interface_property i2cAvs burstOnBurstBoundariesOnly false
set_interface_property i2cAvs burstcountUnits WORDS
set_interface_property i2cAvs explicitAddressSpan 0
set_interface_property i2cAvs holdTime 0
set_interface_property i2cAvs linewrapBursts false
set_interface_property i2cAvs maximumPendingReadTransactions 0
set_interface_property i2cAvs maximumPendingWriteTransactions 0
set_interface_property i2cAvs readLatency 1
set_interface_property i2cAvs readWaitStates 0
set_interface_property i2cAvs readWaitTime 0
set_interface_property i2cAvs setupTime 0
set_interface_property i2cAvs timingUnits Cycles
set_interface_property i2cAvs writeWaitTime 0
set_interface_property i2cAvs ENABLED true
set_interface_property i2cAvs EXPORT_OF ""
set_interface_property i2cAvs PORT_NAME_MAP ""
set_interface_property i2cAvs CMSIS_SVD_VARIABLES ""
set_interface_property i2cAvs SVD_ADDRESS_GROUP ""

add_interface_port i2cAvs avs_i2cAvs_address address Input 2
add_interface_port i2cAvs avs_i2cAvs_write write Input 1
add_interface_port i2cAvs avs_i2cAvs_readdata readdata Output 8
add_interface_port i2cAvs avs_i2cAvs_writedata writedata Input 8
add_interface_port i2cAvs avs_i2cAvs_read read Input 1
set_interface_assignment i2cAvs embeddedsw.configuration.isFlash 0
set_interface_assignment i2cAvs embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment i2cAvs embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment i2cAvs embeddedsw.configuration.isPrintableDevice 0


# 
# connection point i2cInterface
# 
add_interface i2cInterface conduit end
set_interface_property i2cInterface associatedClock i2cClk
set_interface_property i2cInterface associatedReset i2cReset
set_interface_property i2cInterface ENABLED true
set_interface_property i2cInterface EXPORT_OF ""
set_interface_property i2cInterface PORT_NAME_MAP ""
set_interface_property i2cInterface CMSIS_SVD_VARIABLES ""
set_interface_property i2cInterface SVD_ADDRESS_GROUP ""

add_interface_port i2cInterface coe_sclk sclk Bidir 1
add_interface_port i2cInterface coe_sdat sdat Bidir 1


# 
# connection point i2cIrq
# 
add_interface i2cIrq interrupt end
set_interface_property i2cIrq associatedAddressablePoint i2cAvs
set_interface_property i2cIrq associatedClock i2cClk
set_interface_property i2cIrq associatedReset i2cReset
set_interface_property i2cIrq bridgedReceiverOffset ""
set_interface_property i2cIrq bridgesToReceiver ""
set_interface_property i2cIrq ENABLED true
set_interface_property i2cIrq EXPORT_OF ""
set_interface_property i2cIrq PORT_NAME_MAP ""
set_interface_property i2cIrq CMSIS_SVD_VARIABLES ""
set_interface_property i2cIrq SVD_ADDRESS_GROUP ""

add_interface_port i2cIrq ins_i2cIrq_irq irq Output 1

